language: python
python:
  - "2.7"
  - "3.4"
sudo: required
cache: pip
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements-dev.txt"
  - "pip install ."
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27,coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then tox -e py34; fi
